/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ztm_app;
import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author micha
 */
public class FormularzPracownicy extends javax.swing.JFrame {

    /**
     * Creates new form FormularzPracownicy
     */
    private adminWindow adminFormular; 
    private Boolean isToAdd;
    private Connection conn;
    
    public FormularzPracownicy() {
        initComponents();
        this.setLocationRelativeTo(adminFormular);
    }

    public FormularzPracownicy(Connection conn, Integer ID, adminWindow admin, Boolean isToAdd) {
        initComponents();
        this.conn = conn;
        this.adminFormular = admin;
        this.isToAdd = isToAdd;
        nrPracownikaLabel.setText(ID.toString());
        this.setLocationRelativeTo(adminFormular);
        nrPracownikaLabel.setEnabled(true);
    }
    
    public FormularzPracownicy(Connection conn, Pracownicy pracownik, adminWindow admin, Boolean isToAdd) {
        initComponents();
        this.conn = conn;
        this.adminFormular = admin;
        this.isToAdd = isToAdd;
        nrPracownikaLabel.setText(pracownik.getNrPracownika().toString());
        imieLabel.setText(pracownik.getImie());
        nazwiskoLabel.setText(pracownik.getNazwisko());
        miejscowoscLabel.setText(pracownik.getMiejscowosc());
        ulicaLabel.setText(pracownik.getUlica());
        budynekLabel.setText(pracownik.getNrBudynku());
        lokalLabel.setText(pracownik.getNrLokalu());
        telefonLabel.setText(pracownik.getNrTelefonu());
        urodzenieLabel.setText(pracownik.getDataUrodzenia().substring(0, 10));
        zatrudnienieLabel.setText(pracownik.getDataZatrudnienia().substring(0, 10));
        nrZarzadLabel.setText(pracownik.getNrZarzadu().toString());
        nrPocztyLabel.setText(pracownik.getNrPoczty().toString());
        nrStanowiskaLabel.setText(pracownik.getNrStanowiska().toString());
        this.setLocationRelativeTo(adminFormular);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nrPracownikaLabel = new javax.swing.JTextField();
        imieLabel = new javax.swing.JTextField();
        nazwiskoLabel = new javax.swing.JTextField();
        ulicaLabel = new javax.swing.JTextField();
        budynekLabel = new javax.swing.JTextField();
        lokalLabel = new javax.swing.JTextField();
        telefonLabel = new javax.swing.JTextField();
        urodzenieLabel = new javax.swing.JTextField();
        zatrudnienieLabel = new javax.swing.JTextField();
        nrZarzadLabel = new javax.swing.JTextField();
        nrPocztyLabel = new javax.swing.JTextField();
        nrStanowiskaLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        miejscowoscLabel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        commitButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Nr pracownika");

        jLabel3.setText("Imię");

        jLabel4.setText("Nazwisko");

        jLabel5.setText("Ulica");

        jLabel6.setText("Nr budynku");

        jLabel7.setText("Nr lokalu");

        jLabel8.setText("Nr telefonu");

        jLabel9.setText("Data urodzenia");

        jLabel10.setText("Data zatrudnienia");

        jLabel11.setText("Nr zarządu");

        jLabel12.setText("Nr poczty");

        jLabel13.setText("Nr stanowiska");

        nrPracownikaLabel.setEnabled(false);
        nrPracownikaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrPracownikaLabelActionPerformed(evt);
            }
        });

        ulicaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulicaLabelActionPerformed(evt);
            }
        });

        jLabel1.setText("Miejscowość");

        miejscowoscLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miejscowoscLabelActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 34, 34));
        jLabel15.setText("*");

        jLabel16.setForeground(new java.awt.Color(255, 34, 34));
        jLabel16.setText("*");

        jLabel17.setForeground(new java.awt.Color(255, 34, 34));
        jLabel17.setText("*");

        jLabel18.setForeground(new java.awt.Color(255, 34, 34));
        jLabel18.setText("*");

        jLabel19.setForeground(new java.awt.Color(255, 34, 34));
        jLabel19.setText("*");

        jLabel20.setForeground(new java.awt.Color(255, 34, 34));
        jLabel20.setText("*");

        jLabel21.setForeground(new java.awt.Color(255, 34, 34));
        jLabel21.setText("*");

        jLabel22.setForeground(new java.awt.Color(255, 34, 34));
        jLabel22.setText("*");

        jLabel23.setForeground(new java.awt.Color(255, 34, 34));
        jLabel23.setText("*");

        jLabel24.setForeground(new java.awt.Color(255, 34, 34));
        jLabel24.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ulicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lokalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telefonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(urodzenieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nrZarzadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nrPracownikaLabel)
                            .addComponent(nazwiskoLabel)
                            .addComponent(budynekLabel)
                            .addComponent(zatrudnienieLabel)
                            .addComponent(nrPocztyLabel)
                            .addComponent(nrStanowiskaLabel)
                            .addComponent(imieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(miejscowoscLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nrPracownikaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nazwiskoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miejscowoscLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ulicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budynekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lokalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urodzenieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zatrudnienieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrZarzadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrPocztyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrStanowiskaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        infoLabel.setText("Dodawanie/Modyfikacja rekordu w tabeli pracowników");

        commitButton.setText("Commit");
        commitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitButtonActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 34, 34));
        jLabel14.setText("* pole obowiązkowe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(commitButton)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(infoLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nrPracownikaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrPracownikaLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrPracownikaLabelActionPerformed

    private void ulicaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulicaLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ulicaLabelActionPerformed

    private void commitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitButtonActionPerformed
        Pracownicy prac = new Pracownicy();
        
        if (miejscowoscLabel.getText().trim().isEmpty() || budynekLabel.getText().trim().isEmpty() || imieLabel.getText().trim().isEmpty() || nazwiskoLabel.getText().trim().isEmpty() || nrPocztyLabel.getText().trim().isEmpty() || nrStanowiskaLabel.getText().trim().isEmpty() || nrZarzadLabel.getText().trim().isEmpty() || telefonLabel.getText().trim().isEmpty() || zatrudnienieLabel.getText().trim().isEmpty() || miejscowoscLabel.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Obowiązkowe pola nie zostały wypełnione","Błąd",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (ulicaLabel.getText().trim().isEmpty()) prac.setUlica("NULL");
        else prac.setUlica(ulicaLabel.getText().trim());
            
        if (lokalLabel.getText().trim().isEmpty()) prac.setNrLokalu("NULL");
        else  prac.setNrLokalu(lokalLabel.getText().trim());
        
        if (urodzenieLabel.getText().trim().isEmpty()) prac.setDataUrodzenia("NULL");
        else prac.setDataUrodzenia(urodzenieLabel.getText().trim());
        
        try{
            prac.setNrPoczty(Integer.parseInt(nrPocztyLabel.getText().trim()));
            prac.setNrPracownika(Integer.parseInt(nrPracownikaLabel.getText().trim()));
            prac.setNrStanowiska(Integer.parseInt(nrStanowiskaLabel.getText().trim()));
            prac.setNrZarzadu(Integer.parseInt(nrZarzadLabel.getText().trim()));
        }
        
        catch(NumberFormatException exc){
            JOptionPane.showMessageDialog(this,"Wprowadzono niepoprawne dane","Błąd",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        prac.setNrBudynku(budynekLabel.getText().trim());
        prac.setImie(imieLabel.getText().trim());
        prac.setNazwisko(nazwiskoLabel.getText().trim());
        prac.setNrTelefonu(telefonLabel.getText().trim());
        prac.setDataZatrudnienia(zatrudnienieLabel.getText().trim());
        prac.setMiejscowosc(miejscowoscLabel.getText().trim());
        
        if (isToAdd){
            if (prac.addPracownik(conn, prac) != 0){
                JOptionPane.showMessageDialog(this,"Rekord został pomyślnie dodany do bazy danych","Sukces",JOptionPane.INFORMATION_MESSAGE);
                adminFormular.setEnabled(true);
                this.dispose();
            } else 
                JOptionPane.showMessageDialog(this,"Nie udało się dodać rekordu do bazy danych","Błąd",JOptionPane.WARNING_MESSAGE);
        } else {
            if (prac.updatePracownik(conn, prac) != 0){
                JOptionPane.showMessageDialog(this,"Rekord został pomyślnie zmodyfikowany","Sukces",JOptionPane.INFORMATION_MESSAGE);
                adminFormular.setEnabled(true);
                this.dispose();
            } else 
                JOptionPane.showMessageDialog(this,"Nie udało się zmodyfikować rekordu","Błąd",JOptionPane.WARNING_MESSAGE);
        }
        adminFormular.refreshTable();
        
    }//GEN-LAST:event_commitButtonActionPerformed

    private void miejscowoscLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miejscowoscLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miejscowoscLabelActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budynekLabel;
    private javax.swing.JButton commitButton;
    private javax.swing.JTextField imieLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lokalLabel;
    private javax.swing.JTextField miejscowoscLabel;
    private javax.swing.JTextField nazwiskoLabel;
    private javax.swing.JTextField nrPocztyLabel;
    private javax.swing.JTextField nrPracownikaLabel;
    private javax.swing.JTextField nrStanowiskaLabel;
    private javax.swing.JTextField nrZarzadLabel;
    private javax.swing.JTextField telefonLabel;
    private javax.swing.JTextField ulicaLabel;
    private javax.swing.JTextField urodzenieLabel;
    private javax.swing.JTextField zatrudnienieLabel;
    // End of variables declaration//GEN-END:variables
}
